# Generated by Django 4.2.5 on 2023-10-31 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
                ('portfolio_url', models.URLField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='professional_profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
