# Generated by Django 4.2.5 on 2023-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='confirm_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='professional',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='licenses',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='professional',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='professional',
            name='certification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
    ]
